### ISSUE TITLE
Design for Sign In screen

### ISSUE THREAD

**Issue by vivanov1410** [vivanov1410/road-so-far-mobile#13]

**Comment by Kerthara** [comment]
**Sign In screen  mockup** 

![sign-in-v 2](https://cloud.githubusercontent.com/assets/6184057/18030365/229505f4-6c68-11e6-9c8a-2f1188f2dd96.png)

**Comment by Kerthara** [comment]
### Animated button

![signinform-component1](https://cloud.githubusercontent.com/assets/6184057/18407761/0517ec28-76cf-11e6-8e0e-56e3df05af9e.gif)
