### ISSUE TITLE
Design for splash screen

### ISSUE THREAD

**Issue by vivanov1410** [vivanov1410/road-so-far-mobile#15]

**Comment by Kerthara** [comment]
**_Splash Screen v.0.1**_ 

![splash-screen-v 0 1](https://cloud.githubusercontent.com/assets/6184057/17829442/ef5ef276-6663-11e6-8d03-2b08da288ac9.png)

**Comment by vivanov1410** [comment]
I am going to start implementation, can you add this design to zeplin? ❤️

**Comment by Kerthara** [comment]
Sure 🐱  Working on it)

**Comment by Kerthara** [comment]
Check out Zeplin, with **RsF** tag
