### ISSUE TITLE
Design for create fuel purchase

### ISSUE THREAD

**Issue by vivanov1410** [vivanov1410/road-so-far-mobile#33]

**Comment by Kerthara** [comment]
### Create New Fuel Purchase

**1. empty fields**

![new-fuel-purchase](https://cloud.githubusercontent.com/assets/6184057/18228586/263dab28-720a-11e6-9570-e81bd2e0148c.png)

**2. filled form**

![edit-fuel-purchase-filled](https://cloud.githubusercontent.com/assets/6184057/18228591/5c11ab8c-720a-11e6-9072-45e0e76937f4.png)
