### ISSUE TITLE
Design for edit fuel purchase

### ISSUE THREAD

**Issue by vivanov1410** [vivanov1410/road-so-far-mobile#34]

**Comment by Kerthara** [comment]
### Edit Fuel Purchase

> **Quantity**  and **Amount** fields vary depending on **Location** field.
> 
> _If_ **Location** in Canada _then_ **Liters** and **CAD**
> _if_ **Location** in USA _then_ **Gallons** and **USD**

![edit-fuel-purchase-filled](https://cloud.githubusercontent.com/assets/6184057/18228595/8c1f7098-720a-11e6-8e05-be803dcbffea.png)
